version: "2.4"

services:

    web:
      build: .
      command: python ./app/manage.py runserver 0.0.0.0:8080
      volumes:
        - .:/code
      ports:
        - "8080:8080"
      links:
        - db

    db:
      image: mysql:5.7
      expose:
        - "3306"
      volumes:
        - ./db:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=app
        - MYSQL_ROOT_PASSWORD=root
